server:
  port: 8080

spring:
  datasource:
    name: ll
    url: jdbc:mysql://106.53.67.201/ll
    username: fangcheng
    password: Liang@123
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lei.dao


logging:
  level:
    com:
      lei:
        dao: debug